import Head from "next/head";
import styles from "../styles/Home.module.scss";
import LoginContainer from "@/container/login";
import MyNavBar from "@/container/Navbar";
import { useGlobalContext } from "@/store/globalcontext";

export default function Home() {
  const { user } = useGlobalContext();
  return (
    <>
      <Head>
        <title>XC Couronne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavBar />
      <main className={styles.main}>
        <LoginContainer />
      </main>
    </>
  );
}
