import Head from "next/head";
import React from "react";
import MyNavBar from "../Navbar";
import styles from "./MonProfils.module.scss";
export default function MonProfilsContainer() {
  return (
    <>
      <Head>
        <title>XC Couronne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavBar />
      <main className={styles.main}></main>
    </>
  );
}
